budget: 512
num_views: 1
token_per_image: 64
streaming_obs_horizon: 16
pool_type: mean
use_pos_emb: true
use_state_emb: false
memory_feature:
  img:
    net: identity
    input_dim: 2048
  pos:
    input_dim: 768
    hidden_dim: 768
  state:
    input_dim: 8
    hidden_dim: 512
integration_type: expert
memory_token_dim: 1024
representation_type: recurrent
recurrent_memory:
  type: ttt
  hidden_dim: 512
  remat_n_mini_batches: 4
  output_stats: true
  max_recur_steps: 64
  max_pretraj_steps: 40
  ttt_config:
    ttt_type: linear
    num_ttt_heads: 2
    base_lr: 0.01
    max_lr: 0.1
    qk_norm: true
    v_norm: true
    max_grad_norm: 5.0
    remat_n_mini_batches: 4
  rmt_config:
    num_attn_heads: 8
    num_kv_heads: 1
  max_input_tokens: 4096
  mini_batch_size: 64