run_name: HiMem_calvin_stage2
action_head: flowmatching
bridge_himem_config: configs/bridge_himem/experiments/crosskv_clean.yaml
dataset_type: simulation
dataset_config_path: configs/datasets/calvin.yaml
use_augmentation: true
disable_wandb: true
disable_swanlab: true
vlm_name: OpenGVLab/InternVL3-1B

lr: 1.0e-5
dropout: 0.2
weight_decay: 1.0e-3
batch_size: 16
image_size: 448
max_steps: 80000
log_interval: 10
ckpt_interval: 2500
warmup_steps: 1000
grad_clip_norm: 1.0
num_layers: 8
num_workers: 4
horizon: 14
per_action_dim: 24
state_dim: 24

finetune_vlm: true
finetune_action_head: true
save_dir: run_outputs/training/calvin_stage2
